spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivroprod?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root

springdoc:
  api-docs:
    enabled: false