spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null

springdoc:
  packages-to-scan: com.mercadolivro.controller
  swagger-ui:
    path: /swagger.html

jwt:
  secret: 7bc31d13-18b7-4aac-91f5-f5b5731df496
  expiration: 999999